function sumbitForm(){
    var counTry=document.getElementById('country')
    var city=document.getElementById('city')
    var Course=document.getElementById('Course')
    var Stage=document.getElementById('Stage')
    var fullName=document.getElementById('fullName')
    var fatherName=document.getElementById('fatherName')
    var email=document.getElementById('email')
    var phoneNumber=document.getElementById('phoneNumber')
    var cinicNum=document.getElementById('cinicNum')
    var fatherCnic=document.getElementById('fatherCnic')
    var birTh=document.getElementById('birTh')
    var genDer=document.getElementById('genDer')
    var address=document.getElementById('address')
    var qualifiction=document.getElementById('qualifiction')
    var laptop=document.getElementById('laptop')

    console.log(`Country: ${counTry.value}`)
    console.log(`City: ${city.value}`)
    console.log(`Course: ${Course.value}`)
    console.log(`Stage: ${Stage.value}`)
    console.log(`FullName: ${fullName.value}`)
    console.log(`FatherName: ${fatherName.value}`)
    console.log(`Email: ${email.value}`)
    console.log(`PhoneNumber: ${phoneNumber.value}`)
    console.log(`cNIC Nummber: ${cinicNum.value}`)
    console.log(`FatherCNIC: ${fatherCnic.value}`)
    console.log(`Birth: ${birTh.value}`)
    console.log(`Gender: ${genDer.value}`)
    console.log(`Address: ${address.value}`)
    console.log(`Qualifiction: ${qualifiction.value}`)
    console.log(`Laptop: ${laptop.value}`)

}